# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Prevent HIV Oklahoma Policies & Standards
email: policy@preventhivok.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media accounts
social-media:
  github:
    user: PreventHIVOK
    url: https://github.com/{{ include.username }}
  facebook:
    user: PreventHIVOK
    url: https://www.facebook.com/{{ include.username }}
  instagram:
    user: null
    url: https://instagram.com/{{ include.username }}
  twitter:
    user: PreventHIVOK
    url: https://www.twitter.com/{{ include.username }}
  linkedin:
    user: PreventHIVOK
    url: https://linkedin.com/u/{{ include.username }}
  tumbler:
    user: null
    url: https://{{ %username }}.tumbler.com

# Package names
pkg-man:
  gem: jekyll-policy-generator
  npm: jekyll-policy-generator
  composer: preventhivok/org-policy-generator
  bower: jekyll-policy-generator


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
